//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Auctions = new HashSet<Auction>();
            this.Bills = new HashSet<Bill>();
            this.Bid_history = new HashSet<Bid_history>();
        }
    
        public int id { get; set; }
        public int id_role { get; set; }
        [Display(Name = "Username")]
        [Required(ErrorMessage = "Username must be filled")]
        public string username { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password must be filled")]
        public string password { get; set; }
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"[0-9]{3}-[0-9]{3}-[0-9]{4}", ErrorMessage = "Wrong phone patern. Example: 090-123-1234")]
        public string phone { get; set; }
        public bool isActive { get; set; }
        public string avatar { get; set; }
        public Nullable<double> point { get; set; }
        public string email { get; set; }
        public string paypal_account { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid_history> Bid_history { get; set; }
    }
}
